<wsdl:definitions
     name="vers_GL_INTERFACE"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Flux_SOA_Process/csv_to_gl_interface/vers_GL_INTERFACE"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Flux_SOA_Process/csv_to_gl_interface/vers_GL_INTERFACE"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/vers_GL_INTERFACE"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="vers_GL_INTERFACE_plt" >
    <plt:role name="vers_GL_INTERFACE_role" >
      <plt:portType name="tns:vers_GL_INTERFACE_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/vers_GL_INTERFACE" schemaLocation="../Schemas/vers_GL_INTERFACE_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="GlInterfaceCollection_msg">
        <wsdl:part name="GlInterfaceCollection" element="top:GlInterfaceCollection"/>
    </wsdl:message>
    <wsdl:portType name="vers_GL_INTERFACE_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:GlInterfaceCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
