<?xml version="1.0" encoding="UTF-8" ?>
<xsl:stylesheet version="1.0"
                xmlns:xp20="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.Xpath20"
                xmlns:oraxsl="http://www.oracle.com/XSL/Transform/java"
                xmlns:mhdr="http://www.oracle.com/XSL/Transform/java/oracle.tip.mediator.service.common.functions.MediatorExtnFunction"
                xmlns:oraext="http://www.oracle.com/XSL/Transform/java/oracle.tip.pc.services.functions.ExtFunc"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xmlns:oracle-xsl-mapper="http://www.oracle.com/xsl/mapper/schemas"
                xmlns:dvm="http://www.oracle.com/XSL/Transform/java/oracle.tip.dvm.LookupValue"
                xmlns:ns0="http://TargetNamespace.com/fileService" xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xref="http://www.oracle.com/XSL/Transform/java/oracle.tip.xref.xpath.XRefXPathFunctions"
                xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference"
                xmlns:socket="http://www.oracle.com/XSL/Transform/java/oracle.tip.adapter.socket.ProtocolTranslator"
                exclude-result-prefixes="xsi oracle-xsl-mapper xsl xsd ns0 tns xp20 oraxsl mhdr oraext dvm xref socket"
                xmlns:ns1="http://xmlns.oracle.com/pcbpel/adapter/file/Flux_SOA_Process/csv_to_gl_interfaceReal/fileService"
                xmlns:pc="http://xmlns.oracle.com/pcbpel/" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
                xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
                xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                xmlns:ns2="http://xmlns.oracle.com/pcbpel/adapter/db/Flux_SOA_Process/csv_to_gl_interfaceReal/dbReference">
  <oracle-xsl-mapper:schema>
    <!--SPECIFICATION OF MAP SOURCES AND TARGETS, DO NOT MODIFY.-->
    <oracle-xsl-mapper:mapSources>
      <oracle-xsl-mapper:source type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/fileService.wsdl"/>
        <oracle-xsl-mapper:rootElement name="Pieces" namespace="http://TargetNamespace.com/fileService"/>
      </oracle-xsl-mapper:source>
    </oracle-xsl-mapper:mapSources>
    <oracle-xsl-mapper:mapTargets>
      <oracle-xsl-mapper:target type="WSDL">
        <oracle-xsl-mapper:schema location="../WSDLs/dbReference.wsdl"/>
        <oracle-xsl-mapper:rootElement name="GlInterfaceCollection"
                                       namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbReference"/>
      </oracle-xsl-mapper:target>
    </oracle-xsl-mapper:mapTargets>
    <!--GENERATED BY ORACLE XSL MAPPER 12.1.3.0.0(XSLT Build 140529.0700.0211) AT [FRI APR 29 13:38:00 PDT 2016].-->
  </oracle-xsl-mapper:schema>
  <!--User Editing allowed BELOW this line - DO NOT DELETE THIS LINE-->
  <xsl:template match="/">
    <tns:GlInterfaceCollection>
      <xsl:for-each select="/ns0:Pieces/ns0:Piece">
        <tns:GlInterface>
          <tns:status>
            <xsl:value-of select="ns0:status"/>
          </tns:status>
          <tns:ledgerId>
            <xsl:value-of select="ns0:ledger_id"/>
          </tns:ledgerId>
          <tns:accountingDate>
            <xsl:value-of select="ns0:accounting_date"/>
          </tns:accountingDate>
          <tns:currencyCode>
            <xsl:value-of select="ns0:currency_code"/>
          </tns:currencyCode>
          <tns:dateCreated>
            <xsl:value-of select="ns0:date_created"/>
          </tns:dateCreated>
          <tns:createdBy>
            <xsl:value-of select="ns0:created_by"/>
          </tns:createdBy>
          <tns:actualFlag>
            <xsl:value-of select="ns0:actual_flag"/>
          </tns:actualFlag>
          <tns:userJeCategoryName>
            <xsl:value-of select="ns0:user_je_category_name"/>
          </tns:userJeCategoryName>
          <tns:userJeSourceName>
            <xsl:value-of select="ns0:user_je_source_name"/>
          </tns:userJeSourceName>
          <tns:enteredCr>
            <xsl:value-of select="ns0:ENTERED_CR"/>
          </tns:enteredCr>
          <tns:reference1>
            <xsl:value-of select="ns0:REFERENCE1"/>
          </tns:reference1>
          <tns:reference5>
            <xsl:value-of select="ns0:REFERENCE5"/>
          </tns:reference5>
          <tns:periodName>
            <xsl:value-of select="ns0:period_name"/>
          </tns:periodName>
          <tns:codeCombinationId>
            <xsl:value-of select="ns0:CODE_COMBINATION_ID"/>
          </tns:codeCombinationId>
          <tns:setOfBooksId>
            <xsl:value-of select="ns0:set_of_books_id"/>
          </tns:setOfBooksId>
        </tns:GlInterface>
      </xsl:for-each>
    </tns:GlInterfaceCollection>
  </xsl:template>
</xsl:stylesheet>
