<wsdl:definitions
     name="WriteDatabase"
     targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Flux_SOA_Process/Flux_Test5/WriteDatabase"
     xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Flux_SOA_Process/Flux_Test5/WriteDatabase"
     xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/"
     xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/"
     xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/WriteDatabase"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
  <plt:partnerLinkType name="WriteDatabase_plt" >
    <plt:role name="WriteDatabase_role" >
      <plt:portType name="tns:WriteDatabase_ptt" />
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema" >
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/WriteDatabase" schemaLocation="../Schemas/WriteDatabase_table.xsd" />
      </schema>
    </wsdl:types>
    <wsdl:message name="FactureCollection_msg">
        <wsdl:part name="FactureCollection" element="top:FactureCollection"/>
    </wsdl:message>
    <wsdl:portType name="WriteDatabase_ptt">
        <wsdl:operation name="insert">
            <wsdl:input message="tns:FactureCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>
